/**
 * Ponjikkara Cuisine - Malayalam Sadhya Items & Gaslighting Dialogue Database
 * 16 Classic Kerala Onam Sadhya Items with Etiquette vs Ponjikkara Logic
 */

const SADHYA_ITEMS = [
  {
    id: 1,
    nameMl: "പരിപ്പും നെയ്യും",
    nameEn: "Parippu Curry & Ghee",
    icon: "🍲",
    instructionMl: "ചോറിന്റെ മുകളിലേക്ക് നല്ല ചൂട് പരിപ്പും നെയ്യും ഒഴിക്ക് ബ്രോ!",
    instructionEn: "Click on top of the Matta rice to pour Parippu Curry & Ghee!",
    properEtiquette: "Golden dal served directly over center rice mound, followed by hot ghee",
    ponjikkaraLogic: "\"Who puts parippu in the center? Top-right drop onto Pappadam! Catch it if you can!\"",
    wrongTarget: { x: 0.78, y: 0.25 },
    targetName: "Upperi / Pappadam Corner",
    malayalamQuote: "അയ്യോടാ! നീ ചോറ്റിൽ ഒഴിക്കാൻ നോക്കിയ പരിപ്പ് നേരെ പപ്പടത്തിന്റെ പുറത്തേക്ക് ഒഴുകിയല്ലോ! ഞാനാടാ പൊഞ്ചിക്കര!",
    englishQuote: "Oh dear! The Parippu curry you tried to pour on the rice slid straight onto the crunchy Pappadam!",
    color: "#EAB308",
    secondaryColor: "#FEF08A",
    textureType: "liquid_curry",
    splatterRadius: 45,
    crop: { x: 740, y: 420, w: 140, h: 120 }
  },
  {
    id: 2,
    nameMl: "നല്ല ചൂട് സാമ്പാർ",
    nameEn: "Hot Sambar",
    icon: "🥘",
    instructionMl: "ഇനി ചോറിന്റെ ഒത്തനടുക്ക് സാമ്പാർ ഒഴിക്കാം!",
    instructionEn: "Click on the center of the rice mound to pour Sambar!",
    properEtiquette: "Ladled generously over the center heap of steaming Matta rice",
    ponjikkaraLogic: "\"Sambar belongs on the far bottom-right edge of the leaf! Let it drip onto the floor!\"",
    wrongTarget: { x: 0.85, y: 0.75 },
    targetName: "Bottom-Right Edge",
    malayalamQuote: "സാമ്പാർ ചോറ്റിന്റെ നടുക്ക് ഒഴിക്കണം എന്നാണോ നിന്റെ വിചാരം? സാമ്പാർ കൊണ്ടുപോയി ഇലയുടെ അറ്റത്ത് ഒഴിച്ച് താഴേക്ക് ഒഴുക്കും!",
    englishQuote: "Do you think Sambar goes in the center? I'm pouring it on the far edge to leak onto the table!",
    color: "#C2410C",
    secondaryColor: "#F97316",
    textureType: "liquid_curry",
    splatterRadius: 55,
    crop: { x: 580, y: 300, w: 180, h: 150 }
  },
  {
    id: 3,
    nameMl: "അവിയൽ",
    nameEn: "Avial",
    icon: "🥗",
    instructionMl: "ഇലയുടെ മുകളിൽ ഇടത് വശത്ത് പച്ചക്കറികൾ നിറഞ്ഞ അവിയൽ വെക്ക്!",
    instructionEn: "Place Avial on the top-left side of the leaf!",
    properEtiquette: "Placed neatly on the top-left corner of the leaf beside Thoran and Olan",
    ponjikkaraLogic: "\"Top-left is boring! Launching Avial straight to the top-right corner!\"",
    wrongTarget: { x: 0.78, y: 0.22 },
    targetName: "Top Right Corner",
    malayalamQuote: "ഇടത്ത് വെക്കാൻ പറഞ്ഞ അവിയൽ ഞാൻ വലത് വശത്തേക്ക് എറിഞ്ഞു തരും! എന്റെ ശൈലി ചോദ്യം ചെയ്യാൻ നീ വളർന്നോടാ!",
    englishQuote: "I asked for Avial on the left, but I hurled it straight to the top-right corner!",
    color: "#84CC16",
    secondaryColor: "#FEF08A",
    textureType: "solid_mound",
    splatterRadius: 40,
    crop: { x: 590, y: 100, w: 150, h: 150 }
  },
  {
    id: 4,
    nameMl: "തോരൻ",
    nameEn: "Thoran",
    icon: "🥬",
    instructionMl: "അവിയലിന്റെ അടുത്ത് തോരൻ കൊണ്ടിടൂ!",
    instructionEn: "Place Thoran next to Avial on the top edge!",
    properEtiquette: "Served on the top edge of the leaf, adjacent to Avial",
    ponjikkaraLogic: "\"Thoran goes right on top of the crispy Pappadam! Crushing it into powder!\"",
    wrongTarget: { x: 0.24, y: 0.65 },
    targetName: "Pappadam Mound",
    malayalamQuote: "തോരൻ കൊണ്ട് പോയി പപ്പടത്തിന്റെ മുകളിലിട്ട് ചതച്ചരച്ചു! ഇതാണ് പൊഞ്ചിക്കര കേശവന്റെ സ്പെഷ്യൽ തോരൻ അമർത്തൽ!",
    englishQuote: "Dumped the Thoran right on top of the crisp Pappadam and crushed it!",
    color: "#22C55E",
    secondaryColor: "#BBF7D0",
    textureType: "grated_coconut",
    splatterRadius: 35,
    crop: { x: 320, y: 140, w: 120, h: 120 }
  },
  {
    id: 5,
    nameMl: "ഓലൻ",
    nameEn: "Olan",
    icon: "🥥",
    instructionMl: "ഇനി വെള്ളരിക്കയും മത്തങ്ങയും ചേർത്ത ഓലൻ വിളമ്പാം!",
    instructionEn: "Place delicate white Olan in the middle section!",
    properEtiquette: "Delicate ash gourd in coconut milk served gently on the upper section",
    ponjikkaraLogic: "\"Drowning peaceful Olan right into the spicy boiling Sambar pool!\"",
    wrongTarget: { x: 0.82, y: 0.70 },
    targetName: "Bottom Sambar Pool",
    malayalamQuote: "പാവം ശാന്തമായ വെളുത്ത ഓലൻ കൊണ്ട് ഞാൻ ദാ ചൂടുള്ള സാമ്പാറിലേക്ക് മുക്കി കൊന്നു! എങ്ങനെയുണ്ട് എന്റെ വിളമ്പൽ?",
    englishQuote: "Drowned the subtle coconut milk Olan right into the fiery hot Sambar pool!",
    color: "#F8FAFC",
    secondaryColor: "#E2E8F0",
    textureType: "creamy_liquid",
    splatterRadius: 38,
    crop: { x: 470, y: 140, w: 120, h: 120 }
  },
  {
    id: 6,
    nameMl: "കാളൻ",
    nameEn: "Kalan",
    icon: "🍲",
    instructionMl: "നല്ല കുറുക്കിയ കാളൻ ഇലയുടെ മുകളിൽ ഇടണം!",
    instructionEn: "Place thick yellow Kalan on the upper leaf area!",
    properEtiquette: "Thick yellow plantain yogurt curry placed on the top-left side",
    ponjikkaraLogic: "\"Spilling Kalan off the bottom-left edge onto the wooden table! Njan aana kettiya thariyilada!\"",
    wrongTarget: { x: 0.15, y: 0.78 },
    targetName: "Bottom Left Table Edge",
    malayalamQuote: "ഞാൻ ആന കെട്ടിയ തറിയിലാടാ നീ ആട് മേയ്ക്കുന്നത്! ദാ കുറുക്കിയ കാളൻ തറയിലേക്ക് തട്ടിയിട്ടു!",
    englishQuote: "Half of the thick Kalan curry just spilled over the leaf edge onto the wooden table!",
    color: "#EAB308",
    secondaryColor: "#CA8A04",
    textureType: "thick_curry",
    splatterRadius: 42,
    crop: { x: 790, y: 80, w: 130, h: 120 }
  },
  {
    id: 7,
    nameMl: "എരിശ്ശേരി",
    nameEn: "Erissery",
    icon: "🎃",
    instructionMl: "വറുത്തരച്ച എരിശ്ശേരി ഇലയിൽ സമമായി വിളമ്പൂ!",
    instructionEn: "Place roasted coconut Erissery near the center top!",
    properEtiquette: "Mound of pumpkin & toasted coconut placed near the top-center",
    ponjikkaraLogic: "\"Piling Erissery directly on top of Avial! Multiverse curry mixture!\"",
    wrongTarget: { x: 0.78, y: 0.25 },
    targetName: "Avial Mound",
    malayalamQuote: "വറുത്തരച്ച എരിശ്ശേരി എടുത്തു അവിയലിന്റെ തലയിൽ ഇട്ടു! ഇപ്പോ അവിടെ ഒരു മൾട്ടി-വേഴ്‌സ് സദ്യ മിക്സ്ചർ ആയി!",
    englishQuote: "Piled Erissery right on top of Avial! Multiverse food collision!",
    color: "#D97706",
    secondaryColor: "#F59E0B",
    textureType: "solid_mound",
    splatterRadius: 40,
    crop: { x: 720, y: 100, w: 120, h: 120 }
  },
  {
    id: 8,
    nameMl: "പച്ചടി",
    nameEn: "Pachadi (Pineapple/Beetroot)",
    icon: "🟣",
    instructionMl: "പൈനാപ്പിൾ/ബീറ്റ്‌റൂട്ട് പച്ചടി മുകളിൽ ഇടത്ത് വിളമ്പൂ!",
    instructionEn: "Place pink Beetroot/Pineapple Pachadi on top left!",
    properEtiquette: "Sweet pink beetroot/pineapple yogurt curry served on top-left",
    ponjikkaraLogic: "\"Dumping sweet pink Pachadi right into the middle of dry rice!\"",
    wrongTarget: { x: 0.50, y: 0.50 },
    targetName: "Center Rice Mound",
    malayalamQuote: "പിങ്ക് പച്ചടി കൊണ്ട് ഞാൻ ഇലയുടെ ഒത്തനടുക്ക് വീഴ്ത്തി! തമ്പുരാനേ, ചോറിന്റെ മുന്നേ പച്ചടി കഴിക്ക്!",
    englishQuote: "Dumped pink Pachadi right into the middle of the rice! Eat sweet Pachadi first!",
    color: "#EC4899",
    secondaryColor: "#F472B6",
    textureType: "creamy_curry",
    splatterRadius: 45,
    crop: { x: 780, y: 220, w: 140, h: 130 }
  },
  {
    id: 9,
    nameMl: "കിച്ചടി",
    nameEn: "Khichadi (Cucumber Yogurt)",
    icon: "🥒",
    instructionMl: "തൈര് ചേർത്ത കിച്ചടി പച്ചടിയുടെ വശത്ത് വെക്കൂ!",
    instructionEn: "Place Cucumber Khichadi beside Pachadi!",
    properEtiquette: "Cool cucumber yogurt placed beside Pachadi on top-left",
    ponjikkaraLogic: "\"Hurling Khichadi to the extreme bottom-right corner! Don't question my caterer style!\"",
    wrongTarget: { x: 0.88, y: 0.78 },
    targetName: "Far Corner",
    malayalamQuote: "കിച്ചടി താഴെ അറ്റത്തേക്ക് എറിഞ്ഞതാണ് എന്റെ തനത് കൊച്ചിൻ രീതി! കല്യാണരാമൻ ഇത് കണ്ട് പഠിക്കട്ടെ!",
    englishQuote: "Hurled the Khichadi to the bottom far corner! Ponjikkara special style!",
    color: "#A3E635",
    secondaryColor: "#FEF08A",
    textureType: "creamy_curry",
    splatterRadius: 38,
    crop: { x: 780, y: 80, w: 130, h: 120 }
  },
  {
    id: 10,
    nameMl: "ഇഞ്ചിപ്പുളി",
    nameEn: "Inji Puli (Puli Inji)",
    icon: "🫚",
    instructionMl: "സദ്യയുടെ രാജാവായ ഇഞ്ചിപ്പുളി മുകളിൽ അറ്റത്ത് ചെറിയൊരു തുള്ളി തൊടീക്കൂ!",
    instructionEn: "Place a small dab of sweet & sour Inji Puli on the far top-left edge!",
    properEtiquette: "A tiny single drop placed on the top-left tip of the banana leaf",
    ponjikkaraLogic: "\"One drop? I'm dumping the whole bowl of sour Inji Puli all over the rice!\"",
    wrongTarget: { x: 0.48, y: 0.60 },
    targetName: "Main Rice Valley",
    malayalamQuote: "ഒരു ചെറിയ തുള്ളി വെയ്ക്കാൻ പറഞ്ഞ ഇഞ്ചിപ്പുളി ഞാൻ മുഴുവൻ അങ്ങോട്ട് തട്ടിയിട്ടു! ഇനി എരിവും പുളിയും കഴിച്ച് കണ്ണീരൊഴുക്ക്!",
    englishQuote: "Supposed to put a single drop of Inji Puli, but dumped the whole bowl over the rice!",
    color: "#78350F",
    secondaryColor: "#451A03",
    textureType: "thick_syrup",
    splatterRadius: 30,
    crop: { x: 230, y: 140, w: 90, h: 90 }
  },
  {
    id: 11,
    nameMl: "മാങ്ങാ അച്ചാർ",
    nameEn: "Mango Pickle",
    icon: "🥭",
    instructionMl: "എരിവുള്ള കടുമാങ്ങാ അച്ചാർ മുകളിൽ ഇടത് അറ്റത്ത് വെക്കൂ!",
    instructionEn: "Place spicy Mango Pickle at the top-left edge!",
    properEtiquette: "Spicy raw mango pickle dabbed on the top-left leaf border",
    ponjikkaraLogic: "\"Hiding fiery red Mango Pickle inside the coconut Thoran! Surprise explosion!\"",
    wrongTarget: { x: 0.68, y: 0.22 },
    targetName: "Thoran Mound",
    malayalamQuote: "കടുമാങ്ങാ അച്ചാർ എടുത്തു തോരന്റെ മുകളിലേക്ക് വെച്ചു! ഇതൊക്കെ കണ്ട് അടുക്കളയിലുള്ളവർ തലകറങ്ങി വീഴും!",
    englishQuote: "Put spicy Mango Pickle right inside the coconut Thoran!",
    color: "#DC2626",
    secondaryColor: "#EF4444",
    textureType: "chunky_pickle",
    splatterRadius: 28,
    crop: { x: 150, y: 190, w: 90, h: 90 }
  },
  {
    id: 12,
    nameMl: "നാരങ്ങാ അച്ചാർ",
    nameEn: "Naranga Pickle",
    icon: "🍋",
    instructionMl: "നാരങ്ങാ അച്ചാർ മാങ്ങാ അച്ചാറിന്റെ തൊട്ടടുത്ത് വെയ്ക്കൂ!",
    instructionEn: "Place Lemon Pickle next to Mango Pickle!",
    properEtiquette: "Tangy lemon pickle placed beside Mango pickle on top-left",
    ponjikkaraLogic: "\"Dropping oily Lemon Pickle into white coconut milk Olan!\"",
    wrongTarget: { x: 0.80, y: 0.72 },
    targetName: "Olan & Sambar Mix",
    malayalamQuote: "നാരങ്ങാ അച്ചാർ എടുത്തു പായസത്തിന്റെ കുഴിയിലേക്ക് ഇട്ടു! എരിവും പുളിയും മധുരവും കൂടി പൊഞ്ചിക്കര ധമാക്ക!",
    englishQuote: "Dropped oily Lemon Pickle into the delicate white Olan!",
    color: "#CA8A04",
    secondaryColor: "#EAB308",
    textureType: "chunky_pickle",
    splatterRadius: 28,
    crop: { x: 250, y: 10, w: 100, h: 100 }
  },
  {
    id: 13,
    nameMl: "നേന്ത്രക്കായ ചിപ്സ് (ഉപ്പേരി)",
    nameEn: "Banana Chips (Upperi)",
    icon: "🍌",
    instructionMl: "മൊരിഞ്ഞ ഉപ്പേരി ഇലയുടെ താഴെ ഇടത് അറ്റത്ത് വിളമ്പൂ!",
    instructionEn: "Place crunchy Banana Chips on the bottom-left edge!",
    properEtiquette: "Crispy yellow chips placed on the bottom-left corner of the leaf",
    ponjikkaraLogic: "\"Dunking crispy Banana Chips into hot Sambar soup! Vada making time!\"",
    wrongTarget: { x: 0.85, y: 0.75 },
    targetName: "Sambar Pool",
    malayalamQuote: "മൊരിഞ്ഞ ചിപ്സ് കൊണ്ട് സാമ്പാറിൽ ഇട്ടു വട ഉണ്ടാക്കുവാടാ ഞാൻ! ചിപ്സ് മൊത്തം കുതിർന്നു പപ്പടപ്പൊടിയായി!",
    englishQuote: "Dunked the crispy Banana Chips into the hot Sambar pool!",
    color: "#FACC15",
    secondaryColor: "#EAB308",
    textureType: "solid_chips",
    splatterRadius: 35,
    crop: { x: 100, y: 290, w: 80, h: 80 }
  },
  {
    id: 14,
    nameMl: "ശർക്കര വരട്ടി",
    nameEn: "Sharkara Varatti",
    icon: "🟤",
    instructionMl: "ഉപ്പേരിയുടെ അടുത്ത് ശർക്കര വരട്ടി ഇടൂ!",
    instructionEn: "Place jaggery-coated Sharkara Varatti next to Banana Chips!",
    properEtiquette: "Sweet jaggery-coated banana chunks placed beside banana chips on bottom-left",
    ponjikkaraLogic: "\"Plunging sweet Sharkara Varatti into spicy dark Inji Puli mud!\"",
    wrongTarget: { x: 0.45, y: 0.62 },
    targetName: "Inji Puli Mud",
    malayalamQuote: "ശർക്കര വരട്ടി എടുത്തു ഇഞ്ചിപ്പുളിയിൽ കൊണ്ടിട്ടു! മധുരവും എരിവും കൂടി നാക്ക് പുകഞ്ഞു ചാകും!",
    englishQuote: "Dropped sweet Sharkara Varatti directly inside spicy Inji Puli!",
    color: "#451A03",
    secondaryColor: "#78350F",
    textureType: "solid_chips",
    splatterRadius: 30,
    crop: { x: 160, y: 370, w: 80, h: 80 }
  },
  {
    id: 15,
    nameMl: "മൊരിഞ്ഞ പപ്പടം",
    nameEn: "Crispy Pappadam",
    icon: "🫓",
    instructionMl: "ഇലയുടെ താഴെ ഇടത്ത് രാജകീയമായി പപ്പടം വെക്കൂ!",
    instructionEn: "Place the crown jewel Pappadam on the bottom-left corner!",
    properEtiquette: "Puffed golden Pappadam placed proudly on the bottom-left corner",
    ponjikkaraLogic: "\"Trapping the Pappadam directly under 2kg of heavy Matta Rice! Good luck crushing it!\"",
    wrongTarget: { x: 0.50, y: 0.55 },
    targetName: "Under the Rice Mound",
    malayalamQuote: "രാജകീയമായ പപ്പടം കൊണ്ട് ദാ താഴെ അമർത്തി ചതച്ചു വെച്ചു! ഇനി ഇത് ആരെങ്കിലും എടുത്തു പൊടിക്കട്ടെ!",
    englishQuote: "Trapped the crisp Pappadam directly under 2kg of heavy Matta Rice!",
    color: "#FEF08A",
    secondaryColor: "#FACC15",
    textureType: "crispy_pappadam",
    splatterRadius: 50,
    crop: { x: 230, y: 220, w: 150, h: 140 }
  },
  {
    id: 16,
    nameMl: "പാലട പായസം (The Grand Finale)",
    nameEn: "Palada Payasam (The Finale)",
    icon: "🥛",
    instructionMl: "സദ്യയുടെ മാഹാത്മ്യമായ പാലട പായസം ഇലയുടെ താഴെ വലത് വശത്ത് ഒഴിക്കൂ!",
    instructionEn: "Pour the golden Palada Payasam gracefully at the bottom-right corner!",
    properEtiquette: "Poured gracefully on the bottom-right corner as the grand sweet dessert finale",
    ponjikkaraLogic: "\"FLOODING Palada Payasam over pickles, sambar, rice, and the table! TOTAL COLLAPSE!\"",
    wrongTarget: { x: 0.40, y: 0.50 },
    targetName: "Total Leaf Wipeout",
    malayalamQuote: "സദ്യ റെഡി! പാലട പായസം കൊണ്ടുപോയി ഇലയിലുള്ള എല്ലാ അച്ചാറിലും ഒരുപോലെ ഒഴുകി പരന്നു! പൊഞ്ചിക്കര വിന്നർ!",
    englishQuote: "TOTAL SADHYA COLLAPSE! The sweet Palada Payasam flooded over Mango Pickle, Sambar, and the table!",
    color: "#FEF3C7",
    secondaryColor: "#FDE68A",
    textureType: "payasam_flood",
    splatterRadius: 90,
    crop: { x: 0, y: 460, w: 150, h: 110 }
  }
];

function getSadhyaItem(stepIndex) {
  return SADHYA_ITEMS[stepIndex] || SADHYA_ITEMS[0];
}
