/**
 * Ponjikkara Cuisine - Malayalam Sadhya Items & Gaslighting Dialogue Database
 * 16 Classic Kerala Onam Sadhya Items
 */

const SADHYA_ITEMS = [
  {
    id: 1,
    nameMl: "പരിപ്പും നെയ്യും",
    nameEn: "Parippu Curry & Ghee",
    icon: "🍲",
    instructionMl: "ചോറിന്റെ മുകളിലേക്ക് നല്ല ചൂട് പരിപ്പും നെയ്യും ഒഴിക്ക് ബ്രോ!",
    instructionEn: "Click on top of the Matta rice to pour Parippu Curry & Ghee!",
    // Malicious redirection: Target the Pappadam / Banana chips area!
    wrongTarget: { x: 0.22, y: 0.72 },
    targetName: "Upperi / Pappadam Corner",
    malayalamQuote: "അയ്യോടാ! നീ ചോറ്റിൽ ഒഴിക്കാൻ നോക്കിയ പരിപ്പ് നേരെ പപ്പടത്തിന്റെ പുറത്തേക്ക് ഒഴുകിയല്ലോ! ഞാനാടാ പൊഞ്ചിക്കര!",
    manglishQuote: "Ayyoda! Nee chottil ozhikkan nokkiya parippu nere pappadathinte purathekku ozhukiyallo!",
    englishQuote: "Oh dear! The Parippu curry you tried to pour on the rice slid straight onto the crunchy Pappadam and Banana Chips!",
    color: "#EAB308",
    secondaryColor: "#FEF08A",
    textureType: "liquid_curry",
    splatterRadius: 45,
    crop: { x: 740, y: 420, w: 140, h: 120 }
  },
  {
    id: 2,
    nameMl: "നല്ല ചൂട് സാമ്പാർ",
    nameEn: "Hot Sambar",
    icon: "🥘",
    instructionMl: "ഇനി ചോറിന്റെ ഒത്തനടുക്ക് സാമ്പാർ ഒഴിക്കാം!",
    instructionEn: "Click on the center of the rice mound to pour Sambar!",
    // Malicious redirection: Bottom-right far edge!
    wrongTarget: { x: 0.85, y: 0.85 },
    targetName: "Bottom-Right Edge",
    malayalamQuote: "എന്താടാ ഇത്? സാമ്പാർ കൊണ്ടുപോയി വാഴയിലയുടെ അറ്റത്താണോ ഒഴിക്കുന്നത്? മേശപ്പുറത്തേക്ക് ഒലിച്ചിറങ്ങും!",
    manglishQuote: "Enthada ithu? Sambar kondupoi vazhayilayude attathano ozhikkunnath?",
    englishQuote: "What is this? Do you pour Sambar on the far edge of the leaf at your house? It's about to leak onto the table!",
    color: "#C2410C",
    secondaryColor: "#F97316",
    textureType: "liquid_curry",
    splatterRadius: 55,
    crop: { x: 580, y: 300, w: 180, h: 150 }
  },
  {
    id: 3,
    nameMl: "അവിയൽ",
    nameEn: "Avial",
    icon: "🥗",
    instructionMl: "ഇലയുടെ മുകളിൽ ഇടത് വശത്ത് പച്ചക്കറികൾ നിറഞ്ഞ അവിയൽ വെക്ക്!",
    instructionEn: "Place Avial on the top-left side of the leaf!",
    // Malicious redirection: Magnetic drift to top-right corner!
    wrongTarget: { x: 0.80, y: 0.22 },
    targetName: "Top Right Corner",
    malayalamQuote: "ഇടത്ത് വെക്കാൻ പറഞ്ഞ അവിയൽ നീ വലത് വശത്തേക്ക് എറിഞ്ഞു കൊടുത്തോ? ഞാൻ പറഞ്ഞത് കേട്ടില്ലേ?",
    manglishQuote: "Edathu vekkan paranja avial nee valathu vasathekku erinju kodutho?",
    englishQuote: "I asked for Avial on the left, but you launched it all the way to the top-right corner!",
    color: "#84CC16",
    secondaryColor: "#FEF08A",
    textureType: "solid_mound",
    splatterRadius: 40,
    crop: { x: 590, y: 100, w: 150, h: 150 }
  },
  {
    id: 4,
    nameMl: "തോരൻ",
    nameEn: "Thoran",
    icon: "🥬",
    instructionMl: "അവിയലിന്റെ അടുത്ത് തോരൻ കൊണ്ടിടൂ!",
    instructionEn: "Place Thoran next to Avial on the top edge!",
    // Malicious redirection: Land on Parippu & Pappadam!
    wrongTarget: { x: 0.24, y: 0.72 },
    targetName: "Pappadam Mound",
    malayalamQuote: "തോരൻ കൊണ്ട് പോയി പപ്പടത്തിന്റെ മുകളിലിട്ട് ചതച്ചരച്ചല്ലോ മിസ്റ്റർ! ഞാൻ ഇങ്ങനെയേ വിളമ്പൂ!",
    manglishQuote: "Thoran kondu poi pappadathinte mukalilittu chathacharachallo mr!",
    englishQuote: "What chaos! You dumped the Thoran right on top of the crisp Pappadam and crushed it!",
    color: "#22C55E",
    secondaryColor: "#BBF7D0",
    textureType: "grated_coconut",
    splatterRadius: 35,
    crop: { x: 320, y: 140, w: 120, h: 120 }
  },
  {
    id: 5,
    nameMl: "ഓലൻ",
    nameEn: "Olan",
    icon: "🥥",
    instructionMl: "ഇനി വെള്ളരിക്കയും മത്തങ്ങയും ചേർത്ത ഓലൻ വിളമ്പാം!",
    instructionEn: "Place delicate white Olan in the middle section!",
    // Malicious redirection: Splash into Sambar pool at bottom right!
    wrongTarget: { x: 0.82, y: 0.80 },
    targetName: "Bottom Sambar Pool",
    malayalamQuote: "അയ്യോ... പാവം ശാന്തമായ ഓലൻ കൊണ്ട് നീ സാമ്പാറിലേക്ക് മുക്കി കൊന്നല്ലോടോ! പാലും തേങ്ങയും എരിവിൽ മുങ്ങി!",
    manglishQuote: "Ayyo... Paavam shanthamaya olan kondu nee sambarilekku mukki konnallo do!",
    englishQuote: "Oh no... You drowned the subtle coconut milk Olan right into the fiery hot Sambar pool!",
    color: "#F8FAFC",
    secondaryColor: "#E2E8F0",
    textureType: "creamy_liquid",
    splatterRadius: 38,
    crop: { x: 470, y: 140, w: 120, h: 120 }
  },
  {
    id: 6,
    nameMl: "കാളൻ",
    nameEn: "Kalan",
    icon: "🍲",
    instructionMl: "നല്ല കുറുക്കിയ കാളൻ ഇലയുടെ മുകളിൽ ഇടണം!",
    instructionEn: "Place thick yellow Kalan on the upper leaf area!",
    // Malicious redirection: Bottom left table edge!
    wrongTarget: { x: 0.12, y: 0.88 },
    targetName: "Bottom Left Table Edge",
    malayalamQuote: "ഞാൻ ആന കെട്ടിയ തറിയിലാടാ നീ ആട് മേയ്ക്കുന്നത്! കാളൻ മേശപ്പുറത്തേക്ക് ഒലിച്ചിറങ്ങി!",
    manglishQuote: "Njan aana kettiya thariyil aada nee aadu mekkunnath! Kalan thazheppooyi!",
    englishQuote: "Half of the thick Kalan curry just spilled over the leaf edge onto the wooden table!",
    color: "#EAB308",
    secondaryColor: "#CA8A04",
    textureType: "thick_curry",
    splatterRadius: 42,
    crop: { x: 790, y: 80, w: 130, h: 120 }
  },
  {
    id: 7,
    nameMl: "എരിശ്ശേരി",
    nameEn: "Erissery",
    icon: "🎃",
    instructionMl: "വറുത്തരച്ച എരിശ്ശേരി ഇലയിൽ സമമായി വിളമ്പൂ!",
    instructionEn: "Place roasted coconut Erissery near the center top!",
    // Malicious redirection: Splatter on top of Avial!
    wrongTarget: { x: 0.78, y: 0.25 },
    targetName: "Avial Mound",
    malayalamQuote: "എരിശ്ശേരി കൊണ്ട് പോയി അവിയലിന്റെ തലയിൽ ഇട്ടു! ഇപ്പോ അവിടെ സദ്യയല്ല, മൾട്ടി-വേഴ്‌സ് മിക്സ്ചർ ആയി!",
    manglishQuote: "Erissery kondu poi avialinte thalayil ittu! Ippo avide sadhyayalla, multiverse mixture aayi!",
    englishQuote: "You piled Erissery right on top of Avial! Now it's not a Sadhya, it's a multiverse food collision!",
    color: "#D97706",
    secondaryColor: "#F59E0B",
    textureType: "solid_mound",
    splatterRadius: 40,
    crop: { x: 720, y: 100, w: 120, h: 120 }
  },
  {
    id: 8,
    nameMl: "പച്ചടി",
    nameEn: "Pachadi (Pineapple/Beetroot)",
    icon: "🟣",
    instructionMl: "പൈനാപ്പിൾ/ബീറ്റ്‌റൂട്ട് പച്ചടി മുകളിൽ ഇടത്ത് വിളമ്പൂ!",
    instructionEn: "Place pink Beetroot/Pineapple Pachadi on top left!",
    // Malicious redirection: Middle of Matta Rice!
    wrongTarget: { x: 0.50, y: 0.50 },
    targetName: "Center Rice Mound",
    malayalamQuote: "ചോറിന്റെ ഒത്തനടുക്ക് പച്ചടി കൊണ്ട് വീഴ്ത്തി! ഇയാളെ ഏത് ഹോട്ടലിൽ നിന്നാ വിളമ്പാൻ കൊണ്ടുവന്നത്?",
    manglishQuote: "Chottinte nadukku pachadi kondu veezhthi! Ee choru ini aaru thinnum?",
    englishQuote: "You dumped pink Pachadi right into the middle of the rice! Who eats rice soaked in sweet Pachadi first?!",
    color: "#EC4899",
    secondaryColor: "#F472B6",
    textureType: "creamy_curry",
    splatterRadius: 45,
    crop: { x: 780, y: 220, w: 140, h: 130 }
  },
  {
    id: 9,
    nameMl: "കിച്ചടി",
    nameEn: "Khichadi (Cucumber Yogurt)",
    icon: "🥒",
    instructionMl: "തൈര് ചേർത്ത കിച്ചടി പച്ചടിയുടെ വശത്ത് വെക്കൂ!",
    instructionEn: "Place Cucumber Khichadi beside Pachadi!",
    // Malicious redirection: Bottom Right corner!
    wrongTarget: { x: 0.90, y: 0.82 },
    targetName: "Far Corner",
    malayalamQuote: "കിച്ചടി താഴെ അറ്റത്തേക്ക് എറിഞ്ഞതാണ് പൊഞ്ചിക്കരയുടെ ശൈലി! ആരും ചോദ്യം ചെയ്യേണ്ട!",
    manglishQuote: "Khichadi thazhe attathekk erinjathano ponjikkarayude shaili!",
    englishQuote: "Did you intentionally hurl the Khichadi to the bottom far corner? That's Ponjikkara logic!",
    color: "#A3E635",
    secondaryColor: "#FEF08A",
    textureType: "creamy_curry",
    splatterRadius: 38,
    crop: { x: 780, y: 80, w: 130, h: 120 }
  },
  {
    id: 10,
    nameMl: "ഇഞ്ചിപ്പുളി",
    nameEn: "Inji Puli (Puli Inji)",
    icon: "🫚",
    instructionMl: "സദ്യയുടെ രാജാവായ ഇഞ്ചിപ്പുളി മുകളിൽ അറ്റത്ത് ചെറിയൊരു തുള്ളി തൊടീക്കൂ!",
    instructionEn: "Place a small dab of sweet & sour Inji Puli on the far top-left edge!",
    // Malicious redirection: Direct explosion onto Matta Rice!
    wrongTarget: { x: 0.48, y: 0.62 },
    targetName: "Main Rice Valley",
    malayalamQuote: "അയ്യോ! ഒരു തുള്ളി വെയ്ക്കാൻ പറഞ്ഞ ഇഞ്ചിപ്പുളി മുഴുവൻ ചോറിലേക്ക് ഒഴിച്ചു കളഞ്ഞല്ലോ കൃഷ്ണാ! ചോറ് മൊത്തം പുളിച്ചു!",
    manglishQuote: "Ayyo! Oru thulli vekkan paranja injipuli muzhuvan chottilekku ozhichu kalanjallo krishna!",
    englishQuote: "Oh god! You were supposed to put a single drop of Inji Puli, and you dumped the whole bowl over the rice!",
    color: "#78350F",
    secondaryColor: "#451A03",
    textureType: "thick_syrup",
    splatterRadius: 30,
    crop: { x: 230, y: 140, w: 90, h: 90 }
  },
  {
    id: 11,
    nameMl: "മാങ്ങാ അച്ചാർ",
    nameEn: "Mango Pickle",
    icon: "🥭",
    instructionMl: "എരിവുള്ള കടുമാങ്ങാ അച്ചാർ മുകളിൽ ഇടത് അറ്റത്ത് വെക്കൂ!",
    instructionEn: "Place spicy Mango Pickle at the top-left edge!",
    // Malicious redirection: Right into Thoran!
    wrongTarget: { x: 0.70, y: 0.20 },
    targetName: "Thoran Mound",
    malayalamQuote: "മാങ്ങാ അച്ചാർ എടുത്തു തോരന്റെ മുകളിലേക്ക് വെച്ചു! കല്യാണരാമൻ ഇത് കണ്ടാൽ ചിരിച്ചു ചാകും!",
    manglishQuote: "Manga achar eduthu thoraninte mukalilekku vechu! Kalyanaraman ithu kandal chirichu chaagum!",
    englishQuote: "You put spicy Mango Pickle right inside the Thoran! Kalyana Raman would die laughing!",
    color: "#DC2626",
    secondaryColor: "#EF4444",
    textureType: "chunky_pickle",
    splatterRadius: 28,
    crop: { x: 150, y: 190, w: 90, h: 90 }
  },
  {
    id: 12,
    nameMl: "നാരങ്ങാ അച്ചാർ",
    nameEn: "Naranga Pickle",
    icon: "🍋",
    instructionMl: "നാരങ്ങാ അച്ചാർ മാങ്ങാ അച്ചാറിന്റെ തൊട്ടടുത്ത് വെയ്ക്കൂ!",
    instructionEn: "Place Lemon Pickle next to Mango Pickle!",
    // Malicious redirection: Land in Olan / Sambar!
    wrongTarget: { x: 0.78, y: 0.78 },
    targetName: "Olan & Sambar Mix",
    malayalamQuote: "നാരങ്ങാ അച്ചാർ കൊണ്ട് വെളുത്ത ഓലനിലേക്ക് തട്ടിയിട്ടു! എരിവും പുളിയും മധുരവും ഒരൊറ്റ ദുരന്തം!",
    manglishQuote: "Naranga achar konduvannu velutha olanilekku thattiyittu! Erivum puliyum madhuravum ellam koodi dhurantham!",
    englishQuote: "You dropped oily Lemon Pickle into the delicate white Olan! Total culinary disaster!",
    color: "#CA8A04",
    secondaryColor: "#EAB308",
    textureType: "chunky_pickle",
    splatterRadius: 28,
    crop: { x: 250, y: 10, w: 100, h: 100 }
  },
  {
    id: 13,
    nameMl: "നേന്ത്രക്കായ ചിപ്സ് (ഉപ്പേരി)",
    nameEn: "Banana Chips (Upperi)",
    icon: "🍌",
    instructionMl: "മൊരിഞ്ഞ ഉപ്പേരി ഇലയുടെ താഴെ ഇടത് അറ്റത്ത് വിളമ്പൂ!",
    instructionEn: "Place crunchy Banana Chips on the bottom-left edge!",
    // Malicious redirection: Scatter into Sambar pool!
    wrongTarget: { x: 0.84, y: 0.82 },
    targetName: "Sambar Pool",
    malayalamQuote: "ചിപ്സ് കൊണ്ട് സാമ്പാറിൽ ഇട്ടു വട ഉണ്ടാക്കാൻ നോക്കുവാണോ? ഉപ്പേരി മൊത്തം കുതിർന്നു പപ്പടപ്പൊടിയായി!",
    manglishQuote: "Chips kondu sambaril ittu vada undakkan nokkuvano thaan? Upperi motham kuthirnnu!",
    englishQuote: "Are you trying to make soup out of Banana Chips? You dunked the crispy chips into the hot Sambar!",
    color: "#FACC15",
    secondaryColor: "#EAB308",
    textureType: "solid_chips",
    splatterRadius: 35,
    crop: { x: 100, y: 290, w: 80, h: 80 }
  },
  {
    id: 14,
    nameMl: "ശർക്കര വരട്ടി",
    nameEn: "Sharkara Varatti",
    icon: "🟤",
    instructionMl: "ഉപ്പേരിയുടെ അടുത്ത് ശർക്കര വരട്ടി ഇടൂ!",
    instructionEn: "Place jaggery-coated Sharkara Varatti next to Banana Chips!",
    // Malicious redirection: Middle of Inji Puli!
    wrongTarget: { x: 0.45, y: 0.65 },
    targetName: "Inji Puli Mud",
    malayalamQuote: "ശർക്കര വരട്ടി എടുത്തു ഇഞ്ചിപ്പുളിയിൽ കൊണ്ടിട്ടു! മധുരവും എരിവും കൂടി നാക്ക് കരിയും!",
    manglishQuote: "Sharkara varatti eduthu injipuliyil kondittu! Madhuravum erivum koodi naakku pukanju chaagum!",
    englishQuote: "You dropped sweet Sharkara Varatti directly inside spicy Inji Puli! Tongue explosion incoming!",
    color: "#451A03",
    secondaryColor: "#78350F",
    textureType: "solid_chips",
    splatterRadius: 30,
    crop: { x: 160, y: 370, w: 80, h: 80 }
  },
  {
    id: 15,
    nameMl: "മൊരിഞ്ഞ പപ്പടം",
    nameEn: "Crispy Pappadam",
    icon: "🫓",
    instructionMl: "ഇലയുടെ താഴെ ഇടത്ത് രാജകീയമായി പപ്പടം വെക്കൂ!",
    instructionEn: "Place the crown jewel Pappadam on the bottom-left corner!",
    // Malicious redirection: Land directly under the heavy Rice mound!
    wrongTarget: { x: 0.50, y: 0.55 },
    targetName: "Under the Rice Mound",
    malayalamQuote: "ഹഹാ! നല്ല ഒന്നാന്തരം പപ്പടം കൊണ്ട് ചോറിന്റെ അടിയിൽ ചതച്ചു അമർത്തി വെച്ചു! ഇനി ഇത് എങ്ങനെ പൊടിക്കും?",
    manglishQuote: "Hahaha! Nalla onnantharam pappadam kondu chottinte adiyil chathachu amarthivechu!",
    englishQuote: "Hahaha! You trapped the beautiful crisp Pappadam directly under 2kg of heavy Matta Rice!",
    color: "#FEF08A",
    secondaryColor: "#FACC15",
    textureType: "crispy_pappadam",
    splatterRadius: 50,
    crop: { x: 230, y: 220, w: 150, h: 140 }
  },
  {
    id: 16,
    nameMl: "പാലട പായസം (The Grand Finale)",
    nameEn: "Palada Payasam (The Finale)",
    icon: "🥛",
    instructionMl: "സദ്യയുടെ മാഹാത്മ്യമായ പാലട പായസം ഇലയുടെ താഴെ വലത് വശത്ത് ഒഴിക്കൂ!",
    instructionEn: "Pour the golden Palada Payasam gracefully at the bottom-right corner!",
    // Malicious redirection: Slosh over EVERYTHING (Pickles, Sambar, Chips, Floor)!
    wrongTarget: { x: 0.40, y: 0.50 },
    targetName: "Total Leaf Wipeout",
    malayalamQuote: "അയ്യോ സദ്യ തവിടുപൊടിയായി! പായസം കൊണ്ടുപോയി മാങ്ങാ അച്ചാറിലും സാമ്പാറിലും ഒരുപോലെ ഒഴുക്കി! പൊഞ്ചിക്കര സിമുലേറ്റർ വിന്നർ!",
    manglishQuote: "Ayyo sadhya thavidupodiyayi! Payasam kondupoi manga acharilum sambarilum orupole ozhukki!",
    englishQuote: "TOTAL SADHYA COLLAPSE! The sweet Palada Payasam flooded over Mango Pickle, Sambar, and the table! Ponjikkara Disaster Masterclass!",
    color: "#FEF3C7",
    secondaryColor: "#FDE68A",
    textureType: "payasam_flood",
    splatterRadius: 90,
    crop: { x: 0, y: 460, w: 150, h: 110 }
  }
];

function getSadhyaItem(stepIndex) {
  return SADHYA_ITEMS[stepIndex] || SADHYA_ITEMS[0];
}
